name: AERIS DOCS DEPLOY

on:
  push:
    branches:
      - main
      - prod

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build-and-push-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Astro
        run: npm run build

      - name: Push build to prod
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: prod
          folder: dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy-pages:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4